version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - my_network
    ports:
      - "80:80"

  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - my_network

  db:
    container_name: shushu_mysql
    image: mysql:8.0.30
    ports:
      - '3309:3306'
    environment:
      TZ: Asia/Tokyo
      MYSQL_DATABASE: shushu
      MYSQL_USER: test_user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - ./local_db/data:/var/lib/mysql
    networks:
      - common_link

  redis:
    container_name: redis
    image: "redis:latest"
    ports:
      - "6380:6379"
    volumes:
      - "./local_redis/data:/data"
    networks:
      - back

networks:
  my_network:
  common_link:
  back:
